---
# ZFS Installation
#

- hosts: 127.0.0.1
  connection: local

  tasks:
  - include: tasks/prep_env.yml
  - include: tasks/disk_part.yml
  - include: tasks/sys_install.yml
  - include: tasks/sys_config.yml
  - include: tasks/clean_up.yml
