---
# Disk Partitioning

- name: "Install gptfdisk"
  action: shell /usr/bin/dpkg -i zfs-root-ansible/packages/gptfdisk_0.8.5-1_amd64.deb

- name: "Clean all partitions on /dev/sda"
  action: shell /usr/sbin/sgdisk -Z /dev/sda

- name: "Create new partition layout"
  action: shell /sbin/sfdisk -uS /dev/sda < zfs-root-ansible/files/partition_table.dat

- name: "Create ext2 file system on boot partition"
  action: shell /sbin/mke2fs -m 0 -L /boot/grub -j /dev/sda1

- name: "Create the root pool on the second patition"
  action: shell /sbin/zpool create -f rpool /dev/sda2

- name: "Create a ROOT filesystem in the root pool"
  action: shell /sbin/zfs create rpool/ROOT

- name: "Create a descendant filesystem for the Ubuntu system"
  action: shell /sbin/zfs create rpool/ROOT/ubuntu-1

- name: "Dismount all ZFS filesystems"
  action: shell /sbin/zfs umount -a

- name: "Set the mountpoint property on the root filesystem"
  action: shell /sbin/zfs set mountpoint=/ rpool/ROOT/ubuntu-1

- name: "Set the bootfs property on the root pool"
  action: shell /sbin/zpool set bootfs=rpool/ROOT/ubuntu-1 rpool

- name: "Export the pool"
  action: shell /sbin/zpool export rpool
